### PR TITLE
Make more pastel but still visible highlight. Removed easily distiguishable chars. Added <> like

### PR DESCRIPTION
**Pull request by kiwi0fruit**

### CODE REVIEW

**Comment by kiwi0fruit** [comment]
@ohanhi What about this PR?

**Review by WaKeMaTTa — APPROVED** [review]

**Comment by kiwi0fruit** [comment]
by the way: what's wrong with vulgar fractions? I left them in highlighted in this PR but I think they can also be removed.

**Comment by kiwi0fruit** [comment]
Any progress?

**Comment by ohanhi** [comment]
Thanks, published in 1.3.0

**Pull request merged**
